// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV33bJmNfdYBwzgPWVhHMA-0k4cQVS7SI',
    appId: '1:850707190113:web:43068fcad8484b7607f520',
    messagingSenderId: '850707190113',
    projectId: 'trainix-app-mobile',
    authDomain: 'trainix-app-mobile.firebaseapp.com',
    storageBucket: 'trainix-app-mobile.firebasestorage.app',
    measurementId: 'G-4LEBPBYRXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlrvvZUJESIf4TV0sgp-NXwjVQS0iP9WM',
    appId: '1:850707190113:android:37e4fd9b771aa77707f520',
    messagingSenderId: '850707190113',
    projectId: 'trainix-app-mobile',
    storageBucket: 'trainix-app-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1Sg0SK0DXrDygLMs367fQIMk7GjuPILY',
    appId: '1:850707190113:ios:fcb9e9a6b645cbd507f520',
    messagingSenderId: '850707190113',
    projectId: 'trainix-app-mobile',
    storageBucket: 'trainix-app-mobile.firebasestorage.app',
    iosBundleId: 'com.example.trainixApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1Sg0SK0DXrDygLMs367fQIMk7GjuPILY',
    appId: '1:850707190113:ios:fcb9e9a6b645cbd507f520',
    messagingSenderId: '850707190113',
    projectId: 'trainix-app-mobile',
    storageBucket: 'trainix-app-mobile.firebasestorage.app',
    iosBundleId: 'com.example.trainixApp',
  );
}